/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...catchAll]': RouteRecordInfo<
      '/[...catchAll]',
      '/:catchAll(.*)',
      { catchAll: ParamValue<true> },
      { catchAll: ParamValue<false> },
      | never
    >,
    '/academic_years/': RouteRecordInfo<
      '/academic_years/',
      '/academic_years',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/classrooms/': RouteRecordInfo<
      '/classrooms/',
      '/classrooms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/course_offerings/': RouteRecordInfo<
      '/course_offerings/',
      '/course_offerings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/courses/': RouteRecordInfo<
      '/courses/',
      '/courses',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/enrrollments/': RouteRecordInfo<
      '/enrrollments/',
      '/enrrollments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/enrrollments/new': RouteRecordInfo<
      '/enrrollments/new',
      '/enrrollments/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/enrrollments/reprint': RouteRecordInfo<
      '/enrrollments/reprint',
      '/enrrollments/reprint',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/schedules/': RouteRecordInfo<
      '/schedules/',
      '/schedules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/students/': RouteRecordInfo<
      '/students/',
      '/students',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/teachers/': RouteRecordInfo<
      '/teachers/',
      '/teachers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...catchAll].vue': {
      routes:
        | '/[...catchAll]'
      views:
        | never
    }
    'src/pages/academic_years/index.vue': {
      routes:
        | '/academic_years/'
      views:
        | never
    }
    'src/pages/classrooms/index.vue': {
      routes:
        | '/classrooms/'
      views:
        | never
    }
    'src/pages/course_offerings/index.vue': {
      routes:
        | '/course_offerings/'
      views:
        | never
    }
    'src/pages/courses/index.vue': {
      routes:
        | '/courses/'
      views:
        | never
    }
    'src/pages/enrrollments/index.vue': {
      routes:
        | '/enrrollments/'
      views:
        | never
    }
    'src/pages/enrrollments/new.vue': {
      routes:
        | '/enrrollments/new'
      views:
        | never
    }
    'src/pages/enrrollments/reprint.vue': {
      routes:
        | '/enrrollments/reprint'
      views:
        | never
    }
    'src/pages/schedules/index.vue': {
      routes:
        | '/schedules/'
      views:
        | never
    }
    'src/pages/students/index.vue': {
      routes:
        | '/students/'
      views:
        | never
    }
    'src/pages/teachers/index.vue': {
      routes:
        | '/teachers/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
